urls.py
from django.conf.urls.defaults import *
#from ldapAuthBackend import authenticate;
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^change_agent/', include('change_agent.foo.urls')),
    (r'^change_agent/','ldap_login.views.login'),
    (r'^$','ldap_login.views.login'),
    (r'^give_feedback/$','give_feedback.views.index'),
    (r'^manage_feedback/admin$','manage_feedback.views.adminindex'),
    (r'^manage_feedback/createmassforms/$','manage_feedback.views.createmassforms'),
    (r'^ldap_login/$','ldap_login.views.login'), #for authentication
    (r'^ldap_login/logout$','ldap_login.views.logout'), #for loggin out
    (r'^ldap_login/passwordHelp$','ldap_login.views.passwordHelp'),
    (r'^manage_feedback/(?P<errorcode>\d+)/error/$','manage_feedback.views.error'), 
    (r'^manage_feedback/notfilled/$','manage_feedback.views.notFilled'), 
    (r'^manage_feedback/studentsummary$','manage_feedback.views.stusummary'), 
    (r'^give_feedback/(?P<form>\d+)/show/$','give_feedback.views.show'), 
    (r'^give_feedback/(?P<form>\d+)/edit/$','give_feedback.views.editsubmit'), 
    (r'^manage_feedback/(?P<formID>\d+)/feedbackAbout/$','manage_feedback.views.summary'), 
    (r'^manage_feedback/get_user_status/$','manage_feedback.views.get_user_status'),
    (r'^give_feedback/edit/$','give_feedback.views.edit'),
    (r'^give_feedback/edit/$','give_feedback.views.edit'),
    (r'^give_feedback/(?P<submissionID>\d+)/preview.html/$','give_feedback.views.preview'),
    #(r'^manage_feedback/admin/deadline/$','manage_feedback.admin.FeedbackFormAdmin.ChangeDeadline'),
	#(r'^give_feedback/(?P<form>\d+)/preview/$','give_feedback.views.preview'),
	(r'^give_feedback/(?P<form>\d+)/submit/$','give_feedback.views.submit'),    
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
       
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    #(r'^/', include(ldap_login.views.login)), #default is login page
)

if settings.DEBUG:
	# Serve static files in debug.
	urlpatterns += patterns('',
		(r'^change_agent_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT,'show_indexes' : True}),
)

manage_feedback/models.py
from django.db import models
from give_feedback.models import feedbackSubmission

#one feedbackquestion is applicable for many Forms and one Form can have many such questions
class feedbackQuestion(models.Model):
        name = models.CharField("Question Name", max_length=100, help_text='An identifier for the question for internal usage',unique=True);
        text = models.CharField("Question Text", max_length=200,help_text="The actual question");
        
        type = models.CharField(max_length=40, choices=
                ((u'multiple-choice-single-answer',u'Multiple-choice (single answer)'), #render a set of radio buttons
                (u'multiple-choice-multiple-answer',u'Multiple-choice (multiple answer)'),#render a set of checkboxes
                (u'text',u'Open-ended question')) #render a textarea which is wide
        );
        helptext = models.CharField(max_length=100, help_text="The text appears under the question", blank=True, null=True);
        mandatory = models.BooleanField(help_text="Whether you want to keep this field mandatory ?",default=False);

        def __str__(self):
            return ('ID %s %s - %s' % (self.id, self.name, self.type));

#one feedbackQuestionOption belongs to only one feedbackQuestion and that too for types which allow multiple-
class feedbackQuestionOption(models.Model):
        question = models.ForeignKey(feedbackQuestion,limit_choices_to = {'type__startswith':'multiple-'}); #make it applicable only for questions that support multiple choices
        text = models.CharField("Option Text", max_length=200, help_text="Specify the option here");

        def __str__(self):
            return self.text;
     

#one feedbackForm has many questions and it is viewable and fillable by many people
class feedbackForm(models.Model):
        title = models.CharField("Title as it appears to the filler",max_length=100,help_text='Title of the Form as it appears to the filler');
        #allowed_group = we will have a seperate table for relationship
        deadline_for_filling = models.DateTimeField(help_text='Deadline for filling and submitting the form');
        created_on = models.DateTimeField(auto_now_add=True);
        questions = models.ManyToManyField(feedbackQuestion);
        allowed_groups = models.ManyToManyField('ldap_login.group', help_text='Groups which are allowed to view and fill this form') #groups which are allowed to fill this form!
        about = models.ForeignKey('feedbackAbout');
        isofficial = models.BooleanField(default=True,blank=False,null=False, help_text="Is this an official form of SICSR or you are creating it just for your own non-official purpose?");
	sequence = models.CommaSeparatedIntegerField(max_length=100,blank=True,null=False,verbose_name='Sequence of questions',help_text='Sequence in which questions will appear.[ PLEASE ENTER COMMA SEPARATED VALUES ]',default='0')

        def __str__(self):
            return self.title; 

        def formsforUser(self,username): #are you sure it should be here ?
                #take username
                #check what groups are allowed to access this form object
                #
            pass;
        
        def has_been_filled_by_user(self, user):
            '''determines whether the given form was submitted by the give user or not
               if feedback was submitted, returns the feedbackSubmission object
               if feedback was not submitted, returns False

            '''
            try:
                submission = feedbackSubmission.objects.get(feedbackForm=self, submitter=user)
                return submission
            except feedbackSubmission.DoesNotExist as e:
                return False
            except feedbackSubmission.MultipleObjectsReturned as e:
                print 'This single user %s has MULTIPLE submissions!! -- Design problem detected!' % (user)
                print e.msg
                print e
                raise e

	def sortedQuestions(self):
		#if sequence is left empty it shows questions in default format
		if(self.sequence == ''):
                        return self.questions.all()
		else:	
			#get ids of all selected questions
                	selected_question_ids =[]
        	        for q in self.questions.all():
	                        selected_question_ids.append(q.id)

			#split the sequence
			sequence_split = self.sequence.split(',')
			sequence_ids = []
		
			#convert the split sequence into long and store it
			for s in sequence_split:
				sequence_ids.append(long(s))
		
			#endlist stores the ids of questions that are selected but not mentioned in sequence.We will put these ids at the end of sortedlist
			endlist =[]
		
			#ignorelist stores the ids of questions which are in sequence but not selected.We will ignore these questions for now
			ignorelist=[]
		
			#sortedlist stores the ids of questions in sorted order.
			sortedlist=[]

			#Stores ids which are selected but not in sequence
			for x in selected_question_ids:
				if(x in sequence_ids):
					pass
				else:
					endlist.append(x)
			#stores ids which are mentioned in sequence in order
			for y in sequence_ids:
				if(y in selected_question_ids):
					sortedlist.append(y)
				else:
					ignorelist.append(y)

			#stores ids not mentioned in sequence at the end of the sortedlist
			for z in endlist:
				sortedlist.append(z)
		
			sorted_questions = []
			for s in sortedlist:
				sorted_questions.append(feedbackQuestion.objects.get(pk=s))

			return sorted_questions;

	def save(self, *args, **kwargs):
           print "Saving a feedbackForm and putting the right sequence of questions"
          # for q in self.questions.values(): 
          #     self.sequence += q['id']
	   super(feedbackForm, self).save(*args, **kwargs)
	
	def mandatoryQuestions(self):
            """returns a list of mandatory feedbackQuestion in the form"""
            questions = self.questions.filter(mandatory=True);
            questions_dict = {};
            for q in questions:
                questions_dict[q.id] =  q.type;
            
            return questions_dict;

class feedbackAbout(models.Model):
        title = models.CharField("The thing/person about which Feedback is being collected",max_length=40);
        description = models.CharField(max_length=200,help_text="Description");
        #allowed_viewers =  users who are allowed to browse about thsi feedback -- will be back-referenced
        #which form? = which forms are used to collect feedback about this thing/person -- will be back-referenced
        
        def __str__(self):
            return self.title;

class Batch(models.Model):
    sem = ((1,1),(2,2),(3,3),(4,4),(5,5),(6,6))
    batchname = models.CharField(help_text='eg. 2010-12, 2006-09', max_length=7);
    programme = models.CharField('Programme', max_length =10)
    division = models.CharField(help_text='Division or Stream', max_length = 16);
    sem = models.IntegerField(choices = sem)
    course_coordinator = models.ForeignKey('ldap_login.user')
    #subjects = models.ForeignKey('Subject')
    def __str__(self):
        return "%s %s for Sem %d - %s" %(self.programme ,self.batchname ,self.sem, self.division)

    class Meta:
	verbose_name_plural = 'Batches'

class Subject(models.Model):
    name = models.CharField(max_length = 100);
    code = models.CharField(max_length = 15);
    for_batch = models.ForeignKey('Batch')
    taughtby = models.CharField(help_text="Use comma seperated for more than one teacher.",max_length=100)
    def __str__(self):
        return self.name + 'by' + self.taughtby

templates/manage_feedback/adminindex.html
{% extends 'base.html' %}
{% block title%} Home{% endblock%}
{% block content%}

<script language = 'javascript'>
function fillOptions(o)
{
    //alert(o)
    if (o.children.length >= 1) 
       { 
         while(o.firstChild)
             o.removeChild(o.firstChild)
       }
     
    c = document.getElementById('programme_name').value
    
    d = new Date();
    y = d.getFullYear(); //current year
   
    if (c == 'MSC(CA)' || c == 'MBA(IT)')
       {
           //for sem 1 and 2
           options = document.createElement('option')
           options.text = y-1 + '-' + (y+1);
           o.add(options,null)
           if (d.getMonth() > 6){ //for sem 3
               options = document.createElement('option')
               options.text = y + '-' + (y+2);
               o.add(options,null)
            }
            else{ //for sem 4
               options = document.createElement('option')
               options.text = y-2 + '-' + (y);
               o.add(options,null)
            }   

       }
    else
    {
        //for sem 5 and 6
        options = document.createElement('option')
        options.text = (y-2) + '-' + (y+1);
        o.add(options,null)
        //for sem 3 and 4
        options = document.createElement('option')
        options.text = (y-1) + '-' + (y+2);
        o.add(options,null)
        //for sem 1 and 2
        if (d.getMonth() > 6){
            options = document.createElement('option')
            options.text = y + '-' + (y+3);
            o.add(options,null)
        }
        else{
           options = document.createElement('option')
           options.text = y-3 + '-' + (y);
           o.add(options,null)
         }  

    }

}
function enable(c)
{
    
    var ans = confirm('Are you sure??')
    if (ans)
    {
        o = document.getElementById('submit')
        o.removeAttribute('disabled')
        c.value = 'Disable again'
    }
}

</script>

<h3> Hi {{u.username}}!</h3>

{% if formfilled %}
<input type = 'button' value = 'Feedback About this Software' onclick = 'javascript:location.href = "{{ROOT}}/give_feedback/{{f.id}}/show"'>
{% endif %}

<form id = 'MainForm' method = 'post'>
{% csrf_token %}
<b style="font-size:16px">Select Programme:</b>
<select id = 'programme_name' name = 'programme'>
    {% for b in u.batch_set.all %}
        <option>{{b.programme}}</option>
    {% empty %}   
        <option>MSC(CA)</option>
        <option>MBA(IT)</option>
        <option>BBA(IT)</option>
        <option>BCA</option>
    {%endfor%}
</select>

<b style="font-size:16px;">Select Batch:</b>
    <select name = 'batch' required onfocus = 'fillOptions(this)'></select><br/>
<br/>
{% if view_summary or view_notfilled or view_reports %}
<h2>View Batch-wide reports</h2>
{% endif %}
{% if view_summary %}
<input type='button' id='submitbtn' value = "Get Excel Copy of Filled Feedback Forms" onclick = 'changesubmit(this,"{{ROOT}}/manage_feedback/studentsummary")'>
{% endif %}
{% if view_notfilled %}
<input type='button' id='notfilled' value = "Get List of Students who have not filled Forms" onclick = 'changesubmit(this,"{{ROOT}}/manage_feedback/notfilled/")'> 
{% endif %}

{% if view_reports %}
<input type='button' id='reports' value = "Get Summary Report" onclick = 'changesubmit(this,"{{ROOT}}/manage_feedback/summary/")'> 
{% endif %}
<hr/>

{% if create_forms %}
{% if createforms %}
<br/>
<h2>Create Mass Feedback Forms</h2>
<input type = 'radio' name = 'createforms' value = 'all' checked> All 
<input type = 'radio' name = 'createforms' value = 'teachers'> Only Teachers
<input type = 'radio' name = 'createforms' value = 'subjects'> Only Subjects
<br>
Deadline for submissions (YYYY-MM-DD) <input type = 'text' name = 'deadline'size = 10 maxlength =10 value = '2012-10-15'><bR>
<input type = 'button'  id = 'create' value = 'Create Mass Feedback Forms' onclick = 'changesubmit(this,"{{ROOT}}/manage_feedback/createmassforms/")'>
{% endif %}
{% endif %}

{% if view_user_status %}
<hr/>
<h2>View status of all Feedback Forms for an user </h2>
<label for='username'><b>PRN/Username :</b></label>
<input type='text' name='username' />
<input type='button' value='Get status of all Feedback Forms' onclick = 'changesubmit(this,"{% url manage_feedback.views.get_user_status %}")'/>
<hr/>
{% endif %}

</form>
</fieldset> 
<br/>
<i>Please note this<b> feature is Beta </b> and currently under development. We are offering only <b> a preview of the real thing :)</b></li>
</form>
<br/>
<input type = 'button' value = 'logout' onclick = 'javascript:location.href = "{{ROOT}}/ldap_login/logout"'>
{% endblock %}

templates/manage_feedback/date.html
{% extends 'base.html' %}
{% block title %}
    Change the Deadline
{% endblock %}
{% block content %}

<script language = "javascript">
    function fillOptions(o)
    {
        //o=document.getElementById('month');
        if (o.name == 'month')
        {
            var months=new Array('Jan','Feb','Mar','April','May','June','July','Aug','Sept','Oct','Nov','Dec');
          
            for (var i =0;i<12;i++)
            //o.innerHTML += "<option>"+months[i]+"</option>";
            {
                 var option=document.createElement("option");
                 option.text=months[i];
                 o.add(option,null)

            }
        }
        else if(o.name == 'date')
        {
             for (var i =1;i<=31;i++)
            //o.innerHTML += "<option>"+months[i]+"</option>";
            {
                 var option=document.createElement("option");
                 option.text=i;
                 o.add(option,null)

            }
        }
        else if(o.name == 'year')
            {  for (var i =2011;i<2022;i++)
            //o.innerHTML += "<option>"+months[i]+"</option>";
            {
                 var option=document.createElement("option");
                 option.text=i;
                 o.add(option,null)

            }
           }
      }
</script>     

<form action="/manage_feedback/admin/deadline/" method="post">
Select a New Deadline for filling 	
  {% csrf_token %}
  <select name = "date"  onFocus="fillOptions(this);"> </select>
  <select name = "month" onFocus="fillOptions(this);"> </select>
  <select name = "year"  onFocus="fillOptions(this);"> </select>  
 <BR>Date Month Year
 <br><BR>
 <input type="submit" value="Change">       
</form>


{% endblock %}

templates/manage_feedback/feedbackform_list.html
{% extends 'base.html' %}
{% block title %}
 Home Page
{% endblock %}
{% block content %}

<h1> List of Feeback forms </h1>

<ul>
    {% for form in manage_feedback.feedbackForm.all %}
    <li> {{ form }}  </li>
    {% endfor %}
</ul>
{% endblock %}

templates/manage_feedback/informMail.html
{% if user.fullname.strip != '' %}
    Dear <b>{{user.fullname}},</b>
{% else %}
    Dear <b>{{user.username}},</b>
{% endif %}
 
<p> You have following official SICSR Feedback Forms to be filled online : </p>
<ul>
    {% for f in unfilled_forms %}
    <li><a href='http://projects.sdrclabs.in/change_agent/give_feedback/{{f.id}}/show'>{{f.title}}</a></li>
    {% endfor %}
</ul>

Please fill them before their deadline :)
<br>
For any queries, please contact us at : sdrclabs@sicsr.ac.in by putting in [ChangeAgent] in the subject 
line.
<br>
Thanks.
<br><br>
Regards,
<br>
Team ChangeAgent

templates/manage_feedback/notFilled.html
{% extends "base.html" %}
{% block title %} Ppl who havenot filled the form {% endblock %}
{% block content %}
<div id="form" style='text-align:left;'>
{% for k,v in forms_users_dict.items %}
  <b>-------{{ k }}-------</b>
  <br/>
  {% if not v %}
    <i> hurray..!! everybody has filled the form.!!
   {% else %}  
  <ul>
  {% for user in v %}
     <li>{{user.username}} -- {{user.fullname}}</li>
  {% endfor %}  
  </ul>
  {% endif %}
{% endfor %}
<input type='button' value='back' onclick="history.go(-1);return true;">
</div>
<!--<input type = 'button' value="Mail them..!! ">
-->
{% endblock %}

templates/manage_feedback/summary.html
 <title>change_agent::Form {{ formName }} Summary</title>
 <style type = 'text/css'>
    .graph{
        float:right;
        /* border: 1px dotted; */
        width:40%;
        margin-right:62%;
    }
    /*
    .left {
        border: 1px dashed;
        width:60%;
    } */  
    .answers{
        border:2px solid black;
        padding:15;
        width:50%;
    }
    .id{
        float:left;
    } */
</style>
<div id="form">
<h2 align = 'center'> Feedback Summary for feedback about {{ formName }} </h3>
{% for k,v in summaryDict.items %}
 <b><q>Q. {{ k.text|capfirst }}</q></b>
 <br/>
 <ul>
 <div class = 'answers'> 
     <table>
     <tr>
     <td>
      <table>
      {% for option,count in v.items %}
        <tr>
           {% if count == None %}
           <td>
              {% if option != "" %}
                    <li><div class='ans'>{{option}}</div></li>
               {% endif %}
           </td>
           <td> &nbsp; </td>
           {% else %}  
           <td>
             <div class='ans'>{{ option }}</div>
           </td>
           <td>
              <font face = 'verdana' size = '5'><b>{{ count }}</b></font>
           </td>
           {% endif %}
           <!--
           {% comment %}
           <td>
               COUNT: {{count}}
               OPTION : {{option}}
           </td> 
           {% endcomment %}
           -->
        </tr>

      {% endfor %}
      </table>
     </td>
     <td align='right'>
     <div class='graph'>
      {% if k.type != 'text' and count == None %}
         <img src = '{{MEDIA_URL}}/piecharts/{{k.id}}.png'  />
      {% else %}
         <span>&nbsp;</span>
      {% endif %}
     </div>
     </td>
     </tr>
    </table>
 </div>
 </ul>
 <br/>
{% endfor %}
<input type='button' value='back' onClick="history.go(-1); return true;">
</div>

templates/manage_feedback/user_status.html
{% extends "base.html" %}
{% block title %}{{user.fullname}} : Status of Forms {% endblock %}
{% block content %}

<div id="form" style='text-align:left;'>
    <table align='center' border='1'>
        <thead align='center'>
            <tr>
                <td><b>Form Title<b/></td>
                <td><b>Deadline</b></td>
                <td><b>Status</b></td>
            </tr>
        </thead>
        <tbody align='center'>
        {% for form,status in status_of_all_forms.iteritems %}
           <tr class='row_{% cycle 'odd' 'even' %}'>
                {% if status.submitted %}
                <td>{{ form }}</td>
                <td> {{ status.deadline_for_filling|date:"D d M Y"}} </td>
                    <td>{{ status.submitted|yesno:'Submitted,Not Submitted'}} <br/> on <br/> {{ status.submitted_on|date:"D d M Y"}} </td>
                {% else %}
	        <td class='error_text'>{{ form }}</td>
        	<td class='error_text'> {{ status.deadline_for_filling|date:"D d M Y"}} </td>
                <td class='error_text'>{{ status.submitted|yesno:'Submitted,Not Submitted'}}</td>
                {% endif %}
           </tr>
	{% empty %}
           <tr>
                <td colspan='3'>No forms available for this user to fill.</td>
           </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<br/><b>Note:</b> Only those forms which have deadline in current month will be shown here because this feature is still under development.<br/>
<input type='button' onclick="javascript:location.href='{% url manage_feedback.views.adminindex %}'" value="Go back">
{% endblock %}