give_feedback/urls.py
#urls for give_feedback app

from django.conf.urls.defaults import *
from manage_feedback.models import feedbackForm

#info_dict = {
#	'queryset':
info_dict = {
	'queryset' : feedbackForm.objects.all(),
	#should be changed to feedbackForm.allowedforCurrenUser() which will automatically pass the username from the session and bring only those forms....that method is to be defined in the model for feedbackForm
	}

#urlpatterns = patterns('',
#	(r'^$','django.views.generic.list_detail.object_list',info_dict),
#	);

urls.py
from django.conf.urls.defaults import *
#from ldapAuthBackend import authenticate;
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^change_agent/', include('change_agent.foo.urls')),
    (r'^change_agent/','ldap_login.views.login'),
    (r'^$','ldap_login.views.login'),
    (r'^give_feedback/$','give_feedback.views.index'),
    (r'^manage_feedback/admin$','manage_feedback.views.adminindex'),
    (r'^manage_feedback/createmassforms/$','manage_feedback.views.createmassforms'),
    (r'^ldap_login/$','ldap_login.views.login'), #for authentication
    (r'^ldap_login/logout$','ldap_login.views.logout'), #for loggin out
    (r'^ldap_login/passwordHelp$','ldap_login.views.passwordHelp'),
    (r'^manage_feedback/(?P<errorcode>\d+)/error/$','manage_feedback.views.error'), 
    (r'^manage_feedback/notfilled/$','manage_feedback.views.notFilled'), 
    (r'^manage_feedback/studentsummary$','manage_feedback.views.stusummary'), 
    (r'^give_feedback/(?P<form>\d+)/show/$','give_feedback.views.show'), 
    (r'^give_feedback/(?P<form>\d+)/edit/$','give_feedback.views.editsubmit'), 
    (r'^manage_feedback/(?P<formID>\d+)/feedbackAbout/$','manage_feedback.views.summary'), 
    (r'^manage_feedback/get_user_status/$','manage_feedback.views.get_user_status'),
    (r'^give_feedback/edit/$','give_feedback.views.edit'),
    (r'^give_feedback/edit/$','give_feedback.views.edit'),
    (r'^give_feedback/(?P<submissionID>\d+)/preview.html/$','give_feedback.views.preview'),
    #(r'^manage_feedback/admin/deadline/$','manage_feedback.admin.FeedbackFormAdmin.ChangeDeadline'),
	#(r'^give_feedback/(?P<form>\d+)/preview/$','give_feedback.views.preview'),
	(r'^give_feedback/(?P<form>\d+)/submit/$','give_feedback.views.submit'),    
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
       
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    
    #(r'^/', include(ldap_login.views.login)), #default is login page
)

if settings.DEBUG:
	# Serve static files in debug.
	urlpatterns += patterns('',
		(r'^change_agent_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT,'show_indexes' : True}),
)

give_feedback/models.py
from django.db import models

# Create your models here.
class feedbackSubmission(models.Model):
    feedbackForm = models.ForeignKey('manage_feedback.feedbackForm',help_text='Which Form\'s submission?');
    submitter = models.ForeignKey('suvidha.User', help_text='Submitted by which user?'); 
    when = models.DateTimeField(auto_now_add=True, help_text='When was this submitted?');
    def __str__(self):
        return ("%s's submission of form '%s'" % (self.submitter, self.feedbackForm))

class feedbackSubmissionAnswer(models.Model):
    submission = models.ForeignKey('feedbackSubmission',help_text='Submission for which this is the answer');
    question = models.ForeignKey('manage_feedback.feedbackQuestion',help_text='Question for which the answer was submitted');
    answer_option = models.ForeignKey('manage_feedback.feedbackQuestionOption',help_text='The answerOption selected by the user',blank=True,null=True);
    answer_text = models.TextField('Answer text (only for text questions)',help_text='Text answer given by the user(only for text questions',blank=True,null=True);

    def __str__(self):
        return ("%s's answer to '%s' in submission '%s'" % (self.submission.submitter, self.question.text, self.submission.id));	
#limit_choices_to = {'answer.question_id__exact' : question});
    #use add method to insert rows/create instances...right?

manage_feedback/models.py
from django.db import models
from give_feedback.models import feedbackSubmission

#one feedbackquestion is applicable for many Forms and one Form can have many such questions
class feedbackQuestion(models.Model):
        name = models.CharField("Question Name", max_length=100, help_text='An identifier for the question for internal usage',unique=True);
        text = models.CharField("Question Text", max_length=200,help_text="The actual question");
        
        type = models.CharField(max_length=40, choices=
                ((u'multiple-choice-single-answer',u'Multiple-choice (single answer)'), #render a set of radio buttons
                (u'multiple-choice-multiple-answer',u'Multiple-choice (multiple answer)'),#render a set of checkboxes
                (u'text',u'Open-ended question')) #render a textarea which is wide
        );
        helptext = models.CharField(max_length=100, help_text="The text appears under the question", blank=True, null=True);
        mandatory = models.BooleanField(help_text="Whether you want to keep this field mandatory ?",default=False);

        def __str__(self):
            return ('ID %s %s - %s' % (self.id, self.name, self.type));

#one feedbackQuestionOption belongs to only one feedbackQuestion and that too for types which allow multiple-
class feedbackQuestionOption(models.Model):
        question = models.ForeignKey(feedbackQuestion,limit_choices_to = {'type__startswith':'multiple-'}); #make it applicable only for questions that support multiple choices
        text = models.CharField("Option Text", max_length=200, help_text="Specify the option here");

        def __str__(self):
            return self.text;
     

#one feedbackForm has many questions and it is viewable and fillable by many people
class feedbackForm(models.Model):
        title = models.CharField("Title as it appears to the filler",max_length=100,help_text='Title of the Form as it appears to the filler');
        #allowed_group = we will have a seperate table for relationship
        deadline_for_filling = models.DateTimeField(help_text='Deadline for filling and submitting the form');
        created_on = models.DateTimeField(auto_now_add=True);
        questions = models.ManyToManyField(feedbackQuestion);
        allowed_groups = models.ManyToManyField('ldap_login.group', help_text='Groups which are allowed to view and fill this form') #groups which are allowed to fill this form!
        about = models.ForeignKey('feedbackAbout');
        isofficial = models.BooleanField(default=True,blank=False,null=False, help_text="Is this an official form of SICSR or you are creating it just for your own non-official purpose?");
	sequence = models.CommaSeparatedIntegerField(max_length=100,blank=True,null=False,verbose_name='Sequence of questions',help_text='Sequence in which questions will appear.[ PLEASE ENTER COMMA SEPARATED VALUES ]',default='0')

        def __str__(self):
            return self.title; 

        def formsforUser(self,username): #are you sure it should be here ?
                #take username
                #check what groups are allowed to access this form object
                #
            pass;
        
        def has_been_filled_by_user(self, user):
            '''determines whether the given form was submitted by the give user or not
               if feedback was submitted, returns the feedbackSubmission object
               if feedback was not submitted, returns False

            '''
            try:
                submission = feedbackSubmission.objects.get(feedbackForm=self, submitter=user)
                return submission
            except feedbackSubmission.DoesNotExist as e:
                return False
            except feedbackSubmission.MultipleObjectsReturned as e:
                print 'This single user %s has MULTIPLE submissions!! -- Design problem detected!' % (user)
                print e.msg
                print e
                raise e

	def sortedQuestions(self):
		#if sequence is left empty it shows questions in default format
		if(self.sequence == ''):
                        return self.questions.all()
		else:	
			#get ids of all selected questions
                	selected_question_ids =[]
        	        for q in self.questions.all():
	                        selected_question_ids.append(q.id)

			#split the sequence
			sequence_split = self.sequence.split(',')
			sequence_ids = []
		
			#convert the split sequence into long and store it
			for s in sequence_split:
				sequence_ids.append(long(s))
		
			#endlist stores the ids of questions that are selected but not mentioned in sequence.We will put these ids at the end of sortedlist
			endlist =[]
		
			#ignorelist stores the ids of questions which are in sequence but not selected.We will ignore these questions for now
			ignorelist=[]
		
			#sortedlist stores the ids of questions in sorted order.
			sortedlist=[]

			#Stores ids which are selected but not in sequence
			for x in selected_question_ids:
				if(x in sequence_ids):
					pass
				else:
					endlist.append(x)
			#stores ids which are mentioned in sequence in order
			for y in sequence_ids:
				if(y in selected_question_ids):
					sortedlist.append(y)
				else:
					ignorelist.append(y)

			#stores ids not mentioned in sequence at the end of the sortedlist
			for z in endlist:
				sortedlist.append(z)
		
			sorted_questions = []
			for s in sortedlist:
				sorted_questions.append(feedbackQuestion.objects.get(pk=s))

			return sorted_questions;

	def save(self, *args, **kwargs):
           print "Saving a feedbackForm and putting the right sequence of questions"
          # for q in self.questions.values(): 
          #     self.sequence += q['id']
	   super(feedbackForm, self).save(*args, **kwargs)
	
	def mandatoryQuestions(self):
            """returns a list of mandatory feedbackQuestion in the form"""
            questions = self.questions.filter(mandatory=True);
            questions_dict = {};
            for q in questions:
                questions_dict[q.id] =  q.type;
            
            return questions_dict;

class feedbackAbout(models.Model):
        title = models.CharField("The thing/person about which Feedback is being collected",max_length=40);
        description = models.CharField(max_length=200,help_text="Description");
        #allowed_viewers =  users who are allowed to browse about thsi feedback -- will be back-referenced
        #which form? = which forms are used to collect feedback about this thing/person -- will be back-referenced
        
        def __str__(self):
            return self.title;

class Batch(models.Model):
    sem = ((1,1),(2,2),(3,3),(4,4),(5,5),(6,6))
    batchname = models.CharField(help_text='eg. 2010-12, 2006-09', max_length=7);
    programme = models.CharField('Programme', max_length =10)
    division = models.CharField(help_text='Division or Stream', max_length = 16);
    sem = models.IntegerField(choices = sem)
    course_coordinator = models.ForeignKey('ldap_login.user')
    #subjects = models.ForeignKey('Subject')
    def __str__(self):
        return "%s %s for Sem %d - %s" %(self.programme ,self.batchname ,self.sem, self.division)

    class Meta:
	verbose_name_plural = 'Batches'

class Subject(models.Model):
    name = models.CharField(max_length = 100);
    code = models.CharField(max_length = 15);
    for_batch = models.ForeignKey('Batch')
    taughtby = models.CharField(help_text="Use comma seperated for more than one teacher.",max_length=100)
    def __str__(self):
        return self.name + 'by' + self.taughtby

templates/give_feedback/adminindex.html
{% extends 'base.html' %}
{% block title%} Home{% endblock%}
{% block content%}

<script language = 'javascript'>
function fillOptions(o)
{
    if (o.children.length >= 1) 
       { 
         while(o.firstChild)
             o.removeChild(o.firstChild)
       }
    
    c = o.previousElementSibling.value
    d = new Date();
    y = d.getFullYear();
   
    if (c == 'MSc(CA)' || c == 'MBA(IT)')
       {
           options = document.createElement('option')
           options.text = y-1 + ' - ' + y;
           o.add(options,null)
           options = document.createElement('option')
           options.text = y + ' - ' + (y+1);
           o.add(options,null)
       }
    else
    {
         options = document.createElement('option')
         options.text = (y-2) + ' - ' + y;
         o.add(options,null)
        options = document.createElement('option')
        options.text = (y-1) + ' - ' + (y+1);
        o.add(options,null)
        options = document.createElement('option')
        options.text = y + ' - ' + (y+2);
        o.add(options,null)
    }

}

</script>

<form method = 'post' action = 'createmassforms'>
{% csrf_token %}
Programme
<select name = 'programme'>
    <option>MSc(CA)
    <option>MBA(IT)
    <option>BBA(IT)
    <option>BCA
</select>

<select onfocus = 'fillOptions(this)'></select>
SEM
<select name = 'semester'>
    <option>I
    <option>II
    <option>III
    <option>IV
    <option>V
    <option>VI
</select>

<BR>

Create
<input type = 'radio' name = 'createforms' value = 'all'> All 
<input type = 'radio' name = 'createforms' value = 'teachers'> Only Teachers'
<input type = 'radio' name = 'createforms' value = 'subjects'> Only Subjects
<br>
Deadline for submissions - <input type = 'text' name = 'deadline'size = 10 maxlength =10 value = '2011-11-15'><bR>

<input type = 'submit' value = 'create forms'>
</form>
<hr>
<BR><BR>

<form method = 'post' action = 'manage_feedback/studentsummary'>
{% csrf_token %}
Programme
<select name = 'programme'>
    <option>MSc(CA)
    <option>MBA(IT)
    <option>BBA(IT)
    <option>BCA
</select>

<select onfocus = 'fillOptions(this)'></select>
<input type = 'submit' value = 'view Summary'>
</form>
{% endblock %}

templates/give_feedback/form.html
{% extends "base.html" %}
{% block title %}
 Fill the form
{% endblock %}
{% block content %}
<title> Give Your Feedback..!!</title>
<script language='javascript'>

	function mandatory()
	{
	   flag=1;
	   {% for id,type in mandatoryQuestions.items %}
	    {% if type == 'multiple-choice-single-answer' %}
		var radio= document.forms.feedbackForm.q{{id}}_rdb_opt;
		for(i=0;i<radio.length;i++)
		  {          
		      if (radio[i].checked) 
		   {
		       flag=4;
		   }
		  } 
		if(flag!=4) 
		{   
		    alert('Please answer the mandatory radio button questions');
		    radio[0].focus();
		    return false;
		}
	    {% endif %}  
	    {% if type == 'multiple-choice-multiple-answer' %}
	       var check=document.forms.feedbackForm.q2
	       for(i=0;i<check.length;i++)
		   {
		     //alert(check[i].value);
		     if(check[i].checked) 
		       {
		          flag=7;
		       }
		       
		   }
	       if(flag!=7) 
	       {
		   alert('Please answer the mandatory checkbox questions!');
		   check[0].focus();
		   return false;
	       }

	    {% endif %}     
	    {%if type == 'text'%}
		 var a='q{{id}}'
		 var text=document.getElementById(a);
		 if(text.value=="")
		 {
		     alert('Please answer the mandatory text question!');
		     text.focus();
		     return false;
		 }
		 else flag=5;
	    {% endif %}      
	   {% endfor %} 
	 if(flag!=1) return true;
	 else return false;
	}

	function debug(str)
	{
	    alert(str);
	}


</script>
<style type="text/css">

	#disclaimer{
	    font-family:verdana;
	    size:10;
	    text-align:center;
	    color:maroon;
	    
	}
	#formtitle{
			font-family:Calibri;
			size:36;
			text-align:center;
			color:gray;
	}
	

</style>


{% comment %}
<!-- commented by Samar to let people know we aren't spying on them -->
<h3 align='left'> Hi {{ username }} </h3>
{% endcomment %}
<div id="form">
<h1 id="formtitle"> {{ form.title }} </h1>
{% if flag == 'show' %}
  <form name='feedbackForm' action='{{ROOT}}/give_feedback/{{ form.id }}/submit/' method='POST' onsubmit='return mandatory();'>
{% else %}  
  <form name='feedbackForm' action='{{ROOT}}/give_feedback/{{ form.id }}/edit/' method='POST' onsubmit='return mandatory();'>
  <input type='hidden' name='submissionID' value='{{ submissionID }}'>
{% endif %}
	<div align="left" style="padding-left:20px;padding-right:20px;">
	<ol>
		  {% csrf_token %}
	          {% for q in form.sortedQuestions %}		  
		  <li><span><q>{{ q.text }}</q></span>
		      {% if q.mandatory %}
		          <sup><img src="/../change_agent_media/star.gif" height=10 width=10></sup>
		       {% endif %}
		  </li>
		  <br>
		<div style="padding-left:50px;">
			{% if q.type == 'multiple-choice-single-answer' %}
				{% for opt in q.feedbackquestionoption_set.values %}
		          <input type='radio' id = 'q{{q.id}}' name='q{{ q.id }}_rdb_opt' value='{{ opt.id }}'/>
			           <label for='q{{ q.id }}_rdb_opt'>
		      	           <span><ans>{{ opt.text }}</ans></span>
				       </label> <br/>
				  {% endfor %}
			{% endif %}
			{% if q.type == 'multiple-choice-multiple-answer' %}
		          {% for opt in q.feedbackquestionoption_set.values %}
		          <input type='checkbox' id = 'q{{q.id}}' name='q{{ q.id }}_chk_opt{{ opt.id }}'/> 
			           <label for='q{{ q.id }}_chk_opt{{ opt.id }}'>
		      	            <span><ans>{{ opt.text }}</ans></span>
		               </label><br/>
		      	{% endfor %}
			{% endif %}
			{% if q.type == 'text' %}
				<textarea id='q{{q.id}}'name='q{{ q.id }}_txt' rows='12' cols='40' width='30%'></textarea> <br/>
			{% endif %}
			  <br/>
		</div>
		 <br/>
		 {% endfor %}
	</div>
		        <input type='hidden' name='formid' value='{{ form.id }}'> 
		   	<input type='submit' value='Submit feedback!'>
		<input type='button' onclick="javascript:location.href='{{ROOT}}/give_feedback/'" value='Cancel'>
	</form>

{% if form.isofficial %}
    <p id='disclaimer' align='center'>Please note that this form is official feedback form of SICSR.<br/> The questions and their options are all official and the software holds no responsiblity of it.</p>
{% else %}
    <p id='disclaimer' align='center'>Please note that this is an unofficial feedback form and the responses recorded will be available only to the assigned people.</p>
{% endif %}
</div>
{% endblock %}

templates/give_feedback/index.html
{% extends "base.html" %}
{% block title %}
   Home Page
{% endblock %}
{% block content %}
<style type="text/css">
#menubar{
	margin-left:470px;
	}
.fieldset {
	background:rgba(255,240.200,1);	
	border:1px solid rgba(255,187,136);
        border-radius:6px 6px 6px 6px;
	
	-moz-box-shadow:0px 2px 12px rgb(119,85,34);
	-webkit-box-shadow:0px 2px 12px rgb(119,85,34);
	box-shadow:0px 2px 12px rgb(119,85,34);

	color:black;
	margin-bottom:20px;
}
#unfilled{ border:1px solid rgba(104,184,189,0.5);}

#submitted{ border-color:rgb(243,108,32); }

#summary{ border-color:rgb(120,173,96); }
h3{
    font-size:20px;
    font-weight:bold;
}
.tablemajor{
	cellpadding:0px;
	cellspacing:0px;
	border-collapse:collapse;
}
.bookmark-images{
	position:relative;
	left:-10px;
	top:10px;
	margin-bottom:20px;
}
#unfilled tr:first-child{
	border-top:2px solid rgba(104,184,189,0.5);
}
#unfilled .tableelements td{
	font-size:14px;
	color:black;
	padding:16px;
	padding-left:50px;
	border-bottom:2px solid rgba(104,184,189,0.5);
	text-align:left;
}
#submitted tr:first-child{
	border-top:2px solid rgba(243,108,32,0.5);
}
#submitted .tableelements td{
	font-size:14px;
	padding:16px;
	padding-left:50px;
	border-bottom:2px solid rgba(243,108,32,0.5);
	text-align:left;
}
#summary tr:first-child{
	border-top:2px solid rgba(120,173,96,0.5);
}
#summary .tableelements td{
	font-size:14px;
	padding:16px;
	padding-left:50px;	
	border-bottom:2px solid rgba(120,173,96,0.5);
	text-align:center;
}
.tableelements:hover{
	background:rgba(221,221,221,0.4);
	cursor:pointer;
	-moz-box-shadow:0px 0px 5px 5px rgba(204,204,204,0.4) inset;
        -webkit-box-shadow:0px 0px 5px 5px rgba(204,204,204,0.4) inset;
}
</style>
<script>
function changesubmit(o,path)
{
    o.setAttribute('type','submit')
    f = document.getElementById('MainForm')
    f.setAttribute('action',path);
    o.click();
}
</script>
<div id="menubar">
<table>
<tr>
<td>
{% if not About_us_filled %}
<input type="button" class=""  value="Feedback About this Software" onClick="javascript:location.href='{{ROOT}}/give_feedback/16/show'" style="align:left;margin:auto;"><br>
{% endif %}
</td>
<td>
<input type='button' class="" onClick="javascript:location.href='{{ROOT}}/ldap_login/logout'" value='Logout!' alt='Enough of form filling!' style="align:right;margin-left"></span> 
</td>
</tr>
</table>
</div>
<p align="left" style="font-size:18px;margin-left:40px;"> Hi {{u.fullname}}! </p>


<!-- Admin thingies -->

{% if admin %}
<div class="fieldset" id='adminthings'>
<h2> Admin things </h2>
<input type = 'button' onclick ='javascript:location.href = "{{ROOT}}/manage_feedback/admin"' value = 'Admin'>
</fieldset>
{% endif %}

<!-- New feedback forms -->
<div class="fieldset" id='unfilled'>
<img class="bookmark-images" src="{{MEDIA_URL}}/feedback-forms-unfilled-bookmark.png"  width="228pt" height="48pt" align="left"/>
<table class="tablemajor" width='100%' style="margin-top:10px;margin-bottom:20px;">

    {% for form in unfilled_forms %}
      {% if today < form.deadline_for_filling %}
        {% if fill_forms %}
            	<tr onclick="document.location = '{{ROOT}}/give_feedback/{{form.id}}/show';" class="tableelements">
				<td>{{ form.title }}<img align='right' src='{{MEDIA_URL}}/clock' height=20 width=20>
        
        {% else %}
<tr onclick="document.location = '{{ROOT}}/give_feedback/{{form.id}}/show';" class="tableelements">
				<td>{{ form.title }}<img align='right' src='{{MEDIA_URL}}/clock' height=20 width=20>
       {% endif %} 
        </td>
        <td>{{ form.deadline_for_filling|timeuntil }} left </td></tr>
      {% else %}
        <tr class="tableelements">
				<td style="border-right:0px;border-left:0px">{{ form.title }}</td> 
				<td style="border-right:0px;border-left:0px;"> Deadline already exceeded!</td>
			</tr>
      {% endif %}
    {% empty %}
        <i>You have no new feedback forms </i>
    {% endfor %}
</table>
{% comment %}
<p id='disclaimer' align='right'>Please note that all these forms are official feedback forms of SICSR.<br/>The questions, and options are all offical and the sofware hold no responsibilty for the data.</p>
{% endcomment %}
</div>


                <!-- For Preview....-->

{% if view_forms %}
<div class="fieldset" id='submitted'>
<!--h2> Feedback you gave </h2-->
<img class="bookmark-images" src="{{MEDIA_URL}}/feedback-forms-submitted-bookmark.png"  width="238pt" height="48pt" align="left"/>
<table class="tablemajor" width='100%' style="margin-top:10px;margin-bottom:20px;">
    {% for form in filled_forms %}
      {% if today < form.feedbackForm.deadline_for_filling  %}
            {% if fill_forms %}
                <tr onclick="document.location = '{{ROOT}}/give_feedback/{{form.id}}/preview.html';" class="tableelements"> 
			<td>{{form.feedbackForm.title}}</td>
            {% else %} 
                 <<tr class="tableelements"> 
			<td>{{form.feedbackForm.title}}</td>
            {% endif %}
      {% else %}
    <tr onclick="document.location = '{{ROOT}}/give_feedback/{{form.id}}/preview.html';" class="tableelements">
		<td>{{ form.feedbackForm.title }}</td>

      {% endif %} 
	  <td> {{form.feedbackForm.deadline_for_filling|timeuntil }} left</tr>
     {% empty%}
         <h2> You have not filled any forms</h2>
     {% endfor %}
</table>
</div>
{% endif %}
            <!-- Feedback About -->

{% if feedback_about %}
	<div class="fieldset" id='summary'>
	<!--h2> Feedback Form Summary you can view</h2-->
		<img class="bookmark-images" src="{{MEDIA_URL}}/feedback-forms-summary-bookmark.png"  width="238pt" height="48pt" align="left"/>
		<table class="tablemajor" width='100%' style="margin-top:10px;margin-bottom:20px;">
		{% for f in feedback_about %}
			 <tr onclick="document.location = '{{ROOT}}/manage_feedback/{{f.id}}/feedbackAbout';" class="tableelements"><td>{{ f }} </td></tr>
		{% endfor %}
		</table>
	</div>
{% endif %}


{% endblock %}
</body>
</html>

templates/give_feedback/preview.html
{% extends "base.html" %}
{% block title %}
	{{form.title}}
{% endblock %}

{% block content %}
<style type="text/css">
        #disclaimer{
            font-family:verdana;
            size:10;
            text-align:center;
            color:maroon;

        }
        #formtitle{
                        font-family:Calibri;
                        size:36;
                        text-align:center;
                        color:gray;
			padding-bottom:0px;
			margin-bottom:5px;
        }


</style>

<div id="form">

	<h1 id="formtitle"> {{ form.title }} Preview</h1>
	Submitted by {{sub}}

{% regroup submissionDetails by question as question_answers %}
<div align="left" style="padding-left:20px;padding-right:20px;">
	<ol>
	{% for question in question_answers %}
	   <br><li><q>{{ question.grouper }}</q></li>
		{% for item in question.list %}
		   {% if item.answer %}
		      <img src="/change_agent_media/bullet" height='15' width=15> <ans>{{ item.answer }} </ans><br/>
		   {% else %}
      			-
		   {% endif %} 
		{% endfor %}
	{% endfor %}      
	</ol>
</div>
{% if form.deadline_for_filling < date %}
  <br/> <font color='red'>The deadline for filling this form has exceeded! You cannot edit the form.<br/></font>
  <br/>
{% else %}

<form action = "{{ROOT}}/give_feedback/edit/" method='post'>
{% csrf_token %}
<input type='hidden' name='submissionID' value= '{{submissionID}}'>
<input type = "submit" value = "Edit Form">
</form>
{% endif %}
{% if nextform != None %}
<input type='button' onclick="javascript:location.href='{{ROOT}}/give_feedback/{{nextform.id}}/preview.html'" value='Preview next submission'>
{% endif %}

<input type = "submit" value = "Go back to main menu" onclick="javascript:location.href='{{ROOT}}/give_feedback/'">
</div>
{% endblock %}

templates/give_feedback/submit.html
{% extends "base.html" %}
{% block title %}
 Done..
{% endblock %}

{% block content %}
<h3 align='center'> {{ form.title }} </h3>
<h4 align='center'> Thank you for giving us your feedback..!!!! <br> Your feedback is valuable to us..!!</h4>
<br><br><BR>
<!--your submission id is : {{submissionID}}-->
<form action = "{{ROOT}}/give_feedback/{{submissionID}}/preview.html" method = "get">
  <input type="submit" value="View Form Preview">
</form>
{% if nextform != None %}
<input type='button' onclick="javascript:location.href='{{ROOT}}/give_feedback/{{nextform.id}}/show'", value="Go to Next Form"><br/><br/>

<input type='button' onclick="javascript:location.href='{{ROOT}}/give_feedback/'" value="Go back to the main menu">
{% endif %}
{% endblock %}